services:
  - type: web
    name: skillfolio-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    nixpacksPlan:
      aptPackages:
        - wkhtmltopdf
        - fontconfig
        - libxrender1
        - libxext6
        - xfonts-75dpi
        - xfonts-base
        - libjpeg62
